#!/usr/bin/env bash
dry_run="0"

if [ -z "$XDG_CONFIG_HOME" ]; then
    echo "no xdg config hom"
    echo "using ~/.config"
    XDG_CONFIG_HOME=$HOME/.config
fi

if [ -z "$DEV_ENV" ]; then
    echo "env var DEV_ENV needs to be present"
    exit 1
fi

if [[ $1 == "--dry" ]]; then
    dry_run="1"
fi

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN]: $1"
    else
        echo "$1"
    fi
}

log "env: $DEV_ENV"

update_files() {
    local src="$1"
    local dst="${2%/}"

    log "copying over files from: $src -> $dst"
    pushd "$src" &> /dev/null || return 1

    # iterate top-level directories safely
    find . -mindepth 1 -maxdepth 1 -type d -print0 | while IFS= read -r -d '' c; do
        local name="${c#./}"
        local directory="$dst/$name"

        log "    ensure directory: mkdir -p \"$directory\""
        if [[ $dry_run == "0" ]]; then
            mkdir -p "$directory"
        fi

        # sync contents of source dir into destination dir (do NOT rm entire dest)
        log "    syncing: rsync -a --delete-excluded -- \"$c/\" \"$directory/\""
        if [[ $dry_run == "0" ]]; then
            rsync -a -- "$c/" "$directory/"
        fi
    done

    popd &> /dev/null
}

copy() {
    log "removing: $2"
    if [[ $dry_run == "0" ]]; then
        rm $2
    fi
    log "copying: $1 to $2"
    if [[ $dry_run == "0" ]]; then
        cp $1 $2
    fi
}

update_files $DEV_ENV/env/.config $XDG_CONFIG_HOME
update_files $DEV_ENV/env/.local $HOME/.local
update_files $DEV_ENV/env/.ssh $HOME/.ssh

copy $DEV_ENV/tmux-sessionizer/tmux-sessionizer $HOME/.local/scripts/tmux-sessionizer
copy $DEV_ENV/env/.zsh_profile $HOME/.zsh_profile
copy $DEV_ENV/env/.zshrc $HOME/.zshrc
copy $DEV_ENV/env/.tmux-sessionizer $HOME/.tmux-sessionizer
copy $DEV_ENV/dev-env $HOME/.local/scripts/dev-env

sleep 1
hyprctl reload
sleep 0.5
touch $HOME/.config/quickshell/ii/shell.qml
