#!/usr/bin/env bash

pushd $HOME/Personal/.dotfiles/env/.config/nvim
git add .
git commit -m 'automated dev commit'
git push origin main
popd

pushd $HOME/Personal/.dotfiles
git add .
git commit -m 'automated dev commit'
git push origin main
popd

