#!/usr/bin/env bash

sudo pacman -S --needed git base-devel
git clone https://aur.archlinux.org/yay.git
pushd yay
makepkg -si
popd

sudo pacman -S --noconfirm curl wget grep less gzip tar unzip gvim make wl-clipboard tldr openssh

sudo pacman -S --noconfirm fcitx5 fcitx5-bamboo
sudo pacman -S --noconfirm ca-certificates gnupg

yay -S --noconfirm cloudflared kitty-git
