#!/usr/bin/env bash

curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

nvm install --lts

curl -fsSL https://deno.land/install.sh | sh
curl -fsSL https://bun.sh/install | bash

